#!/bin/bash 
# findGreater prints the name of the file that contains a larger number of lines with the 
# the occurrence of the word

if [ ${#} -ne 3 ]; then
  echo "Usage: $0 require 3 arg" 1>&2
  exit 1
fi 

findgreater () {
  if [ $1 -eq $2 ] ; then
   echo "$3" "$4"
  else
   if [ $1 -gt $2 ] ; then
    echo "$3"
   else
    echo "$4"
   fi
 fi
}

findgreater $(egrep $1 $2 | wc -l) $(egrep $1 $3 | wc -l) $2 $3



